# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'design' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for design
    pod ’CarbonKit'
    pod 'SDWebImage'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'M13Checkbox'
    pod 'MBCircularProgressBar'
end
